[WriterReviewNeeded] Update example code and user guide.
ni/semi-test-library-dotnet pull request #176
Opened 2024-12-10 07:18 UTC by lornazh

### What does this Pull Request accomplish?

This pull request updates the example code and user guide page regarding sharing data between code modules.

### Why should this Pull Request be merged?

We are updating these files so that they match the latest capabilities of the STL.

### What testing has been done?

N/A

2024-12-10 07:21 UTC, lornazh commented
I'm not approving the pre pipeline for run because it will fail without Abstractions dll update. @Mattjet27

2024-12-23 05:22 UTC, lornazh commented
@Mattjet27 this change is ready for review.

2024-12-26 11:25 UTC, Mattjet27 commented
> @Mattjet27 this change is ready for review.

@lornazh, this looks good, but I do have one small suggestion. I think it will be preferable and more readable if we did not use the `var` keyword in these examples, but instead used the explicit types we expect back from the Get methods `SiteData<double>` and `PinSiteData<double>`. I think for this case, it would be better practice.

2024-12-26 11:27 UTC, Mattjet27 requested changes
> @Mattjet27 this change is ready for review.

@lornazh, this looks good, but I do have one small suggestion. I now think it will be preferable and more readable if we did not use the `var` keyword in these examples, but instead used the explicit types we expect back from the Get methods `SiteData<double>` and `PinSiteData<double>`. I think for this case, it would be better practice.

2024-12-27 11:36 UTC, Mattjet27 approved these changes

2025-01-02 02:58 UTC, lornazh commented on docs/UserGuide/advanced/SharingPinSiteDataBetweenCodeModules.md
> +    SiteData<bool> resultsToPublish = comparisonResults.Select(result => result.All(value => value == true));
@Mattjet27 I modified the implementation of this method (fetch with the input `samplesToRead` parameter, and handling sequential compare so that publish won't fail). Please be aware and confirm this is what we want to demonstrate to customers.

2025-01-02 11:51 UTC, Mattjet27 approved these changes

2025-01-02 11:51 UTC, Mattjet27 commented on docs/UserGuide/advanced/SharingPinSiteDataBetweenCodeModules.md
> +    SiteData<bool> resultsToPublish = comparisonResults.Select(result => result.All(value => value == true));
@lornazh, noted, this looks correct. However, my suggestion, as shown below, would be to provide a more meaningful variable name instead of `resultsToPublish`, and perhaps add a comment so that it is clear why this is being done. Also, I don't think you need to have `result.All(value => value == true)`, as this could be simplified to `result.All(value => value)`, unless it is intentional for added readability, 
```C#
// Publish the Aggregate Comparison Result, whether or not all samples in the comparison result are where found to be True.
SiteData<bool> aggregateComparisonResults = comparisonResults.Select(result => result.All(value => value));
```

2025-01-03 02:00 UTC, lornazh commented on docs/UserGuide/advanced/SharingPinSiteDataBetweenCodeModules.md
> +    SiteData<bool> resultsToPublish = comparisonResults.Select(result => result.All(value => value == true));
Yes, using `value == true` is intentional for better readability. I simplified it as suggested, now that a comment is added.

2025-01-03 02:21 UTC, merged

2025-01-10 14:26 UTC, Mattjet27 commented on docs/UserGuide/advanced/SharingPinSiteDataBetweenCodeModules.md
> +    semiconductorModuleContext.PublishResults(resultsToPublish, "ComparisonResults");
@lornazh, we missed this, it should have changed to "aggregateComparisonResult" to match the new variable name just above this. Please open a new PR to address this.